apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::794038256791:role/general-eks-node-group-20250323033421308900000001
      username: system:node:{{EC2PrivateDNSName}}
      
    - groups:
      - system:masters
      rolearn: arn:aws:iam::794038256791:role/GitHubActionsECRRole
      username: github-actions-user
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
