apiVersion: v1
kind: Service
metadata:
  name: freshmart
  namespace: freshmart
spec:
  type: ClusterIP  # Change from LoadBalancer to ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: freshmart
